language: nix
os:
  - linux
  - osx
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  target-branch: master
  repo: typedefs/typedefs-docs
  fqdn: docs.typedefs.com
  github-token: $GITHUB_TOKEN
  local-dir: $TRAVIS_BUILD_DIR/result/share/doc/typedefs/
  on:
    branch: publish-docs
